let dados = [
    {
        titulo: "Charmander - #004",
        titulo2: "1ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: "Características: Um pequeno lagarto laranja com uma chama na ponta da cauda. <br> A chama em sua cauda indica sua vitalidade.",
        evolucao: "Evoluções: Charmeleon (#005) e Charizard (#006).",
        personalidade:" Personalidade: Charmander é conhecido por sua coragem e determinação.",
        imagem: "./img/shopping.webp",
        imagem2: "./img/charmeleonpng.png",
        imagem3: "./img/charizard.png",
        tipoClasse: "fogo"
    },
    {
        titulo: "Bulbasaur - #001",
        titulo2: "1ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características: Uma pequena criatura verde com uma semente nas costas. <br> A semente nas suas costas cresce com ele, eventualmente se transformando em uma flor.",
        evolucao: "Evoluções: Ivysaur (#002) e Venusaur (#003)",
        personalidade: "Personalidade: Bulbasaur é conhecido por sua natureza calma e paciente.",
        imagem: "./img/bulbasaur.png",
        imagem2: "./img/ivysaur.png",
        imagem3: "./img/venusaur1.png",
         tipoClasse: "planta"
    },
    {
        titulo: "Squirtle - #007",
        titulo2: "1ª Geração",
        tipo: "Tipo: Água.",
        descricao: "Características: Uma pequena tartaruga azul com um casco resistente. <br> Adora se esconder dentro de seu casco.",
        evolucao: "Evoluções: Wartortle (#008) e Blastoise (#009)",
        personalidade: "Personalidade: Squirtle é conhecido por sua natureza brincalhona e despreocupada.",
        imagem: "./img/squirtle.png",
        imagem2: "./img/wartortle.png",
        imagem3: "./img/blastoise.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Chikorita - #152",
        titulo2: "2ª Geração",
        tipo: "Tipo: Planta.",
        descricao: "Características: Um Pokémon planta com uma folha verde em sua cabeça.",
        evolucao: "Evoluções: Bayleef (#153) e Meganium (#154).",
        personalidade:" Personalidade:  Natureza gentil e calma",
        imagem: "./img/chikorita.png",
        imagem2: "./img/bayleef.png",
        imagem3: "./img/meganium.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Cyndaquil - #155",
        titulo2: "2ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características: Um pequeno Pokémon fogo com uma chama em suas costas. ",
        evolucao: "Evoluções: Quilava (#156) e Typhlosion (#157).",
        personalidade:" Personalidade:  É curioso e gosta de explorar.",
        imagem: "./img/cyndaquil.png",
        imagem2: "./img/quilava.png",
        imagem3: "./img/typhlosion.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Totodile - #158",
        titulo2: "2ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características: Um pequeno crocodilo com dentes afiados.  ",
        evolucao: "Evoluções:  Croconaw (#159) e Feraligatr (#160).",
        personalidade:" Personalidade: É enérgico e adora brincar na água.",
        imagem: "./img/totodile.png",
        imagem2: "./img/croconaw.png",
        imagem3: "./img/feraligatr.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Treecko - #252",
        titulo2: "3ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características: Um pequeno lagarto verde com uma folha na cabeça. <br> É ágil e rápido, adaptando-se bem às florestas densas de Hoenn.  ",
        evolucao: "Evoluções:  Grovyle (#253) e Sceptile (#254).",
        personalidade:" Personalidade:  Ágil, curioso e um pouco tímido..",
        imagem: "./img/treecko.png",
        imagem2: "./img/grovyle.png",
        imagem3: "./img/sceptile.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Torchic - #255",
        titulo2: "3ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características: Um pintinho de fogo com uma chama ardente em sua cabeça. <br> É cheio de energia e adora batalhar. ",
        evolucao: "Evoluções:  Combusken (#256) e Blaziken (#257).",
        personalidade:" Personalidade: Enérgico, corajoso e um pouco impulsivo.",
        imagem: "./img/torchic.png",
        imagem2: "./img/combusken.png",
        imagem3: "./img/blaziken.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Mudkip - #258",
        titulo2: "3ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características: Um pequeno anfíbio azul com barbatanas. <br> É calmo e gosta de explorar rios e lagos.  ",
        evolucao: "Evoluções:  Marshtomp (#259) e Swampert (#260).",
        personalidade:" Personalidade: Calmo, gentil e amigável.",
        imagem: "./img/mudkip.png",
        imagem2: "./img/marshtomp.png",
        imagem3: "./img/swampert.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Turtwig - #387",
        titulo2: "4ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características: Uma pequena tartaruga com uma folha em suas costas. ",
        evolucao: "Evoluções:  Grotle (#388) e Torterra (#389).",
        personalidade:" Personalidade:  Paciente, resistente e um pouco tímido.",
        imagem: "./img/turtwig.png",
        imagem2: "./img/grotle.png",
        imagem3: "./img/torterra.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Chimchar - #290",
        titulo2: "4ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características:Um pequeno macaco de fogo com uma chama na ponta da cauda.  ",
        evolucao: "Evoluções:  Monferno (#391) e Infernape (#392).",
        personalidade:" Personalidade: Confiante, competitivo e um pouco arrogante.",
        imagem: "./img/chimchar.png",
        imagem2: "./img/monferno.png",
        imagem3: "./img/infernape.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Piplup - #393",
        titulo2: "4ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características: Um pequeno pinguim com uma crista em sua cabeça.  ",
        evolucao: "Evoluções:  Prinplup (#394) e Empoleon (#395).",
        personalidade:" Personalidade:  Elegante, orgulhoso e um pouco reservado.",
        imagem: "./img/piplup.png",
        imagem2: "./img/prinplup.png",
        imagem3: "./img/empoleon.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Snivy - #495",
        titulo2: "5ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características: Uma pequena serpente verde com uma flor na cabeça.  ",
        evolucao: "Evoluções:  Servine (#496) e Serperior (#497).",
        personalidade:" Personalidade:  Elegante, confiante e um pouco orgulhoso.",
        imagem: "./img/snivy.png",
        imagem2: "./img/servine.png",
        imagem3: "./img/serperior.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Tepig - #498",
        titulo2: "5ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características: Um pequeno porquinho com uma chama em espiral nas costas. ",
        evolucao: "Evoluções:  Pignite (#499) e Emboar (#500).",
        personalidade:" Personalidade:  Enérgico, competitivo e um pouco imprudente.",
        imagem: "./img/tepig1.png",
        imagem2: "./img/pignite.png",
        imagem3: "./img/emboar.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Oshawott - #501",
        titulo2: "5ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características:Uma lontra com uma concha em forma de chapéu.  ",
        evolucao: "Evoluções:  Dewott (#502) e Samurott (#503).",
        personalidade:" Personalidade: Gentil, amigável e um pouco tímido.",
        imagem: "./img/oshawott.png",
        imagem2: "./img/dewott.png",
        imagem3: "./img/samurott.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Chespin - #650",
        titulo2: "6ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características: Um ouriço com uma casca em forma de castanha.  ",
        evolucao: "Evoluções: Quilladin (#651) e Chesnaught (#652).",
        personalidade:" Personalidade: É calmo e um pouco preguiçoso.",
        imagem: "./img/chespin.png",
        imagem2: "./img/quilladin.png",
        imagem3: "./img/chesnaught.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Fennekin - #653",
        titulo2: "6ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características: Uma raposa com orelhas pontudas e uma cauda flamejante.  ",
        evolucao: "Evoluções:  Braixen (#654) e Delphox (#655).",
        personalidade:" Personalidade: Inteligente, curiosa e um pouco tímida.",
        imagem: "./img/fennekin.png",
        imagem2: "./img/braixen.png",
        imagem3: "./img/delphox.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Froakie - #656",
        titulo2: "6ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características: Uma rã com uma língua comprida e afiada.",
        evolucao: "Evoluções:  Frogadier (#657) e Greninja (#658).",
        personalidade:" Personalidade: Enérgico, travesso e um pouco impulsivo.",
        imagem: "./img/froakie.png",
        imagem2: "./img/frogadier.png",
        imagem3: "./img/greninja.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Rowlet - #722",
        titulo2: "7ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características: Uma coruja pequena e fofa com penas macias.",
        evolucao: "Evoluções:  Dartrix (#723) e Decidueye (#724).",
        personalidade:" Personalidade: Calma, observadora e um pouco tímida.",
        imagem: "./img/rowlet.png",
        imagem2: "./img/dartrix.png",
        imagem3: "./img/decidueye.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Litten - #725",
        titulo2: "7ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características: Um gatinho de fogo com uma pelagem macia e quente.",
        evolucao: "Evoluções:  Torracat (#726) e Incineroar (#727).",
        personalidade:" Personalidade: Rebelde, confiante e um pouco arrogante.",
        imagem: "./img/litten.png",
        imagem2: "./img/torracat.png",
        imagem3: "./img/incineroar.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Popplio - #728",
        titulo2: "7ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características:  Uma foca alegre e energética com uma bola rosa na cabeça. <br> Adora se apresentar e fazer novos amigos.",
        evolucao: "Evoluções:  Brionne (#729) e Primarina (#730).",
        personalidade:" Personalidade: Alegre, extrovertida e um pouco dramática.",
        imagem: "./img/popplio.png",
        imagem2: "./img/brionne.png",
        imagem3: "./img/primarina.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Grookey - #810",
        titulo2: "8ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características:  Um pequeno macaco verde com um galho de árvore como um bastão.",
        evolucao: "Evoluções:  Thwackey (#811) e Rillaboom (#812).",
        personalidade:" Personalidade: Brincalhão, enérgico e um pouco distraído.",
        imagem: "./img/grookey.png",
        imagem2: "./img/thwackey.png",
        imagem3: "./img/rillaboom.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Scorbunny - #813",
        titulo2: "8ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características:  Um coelho de fogo com orelhas compridas e uma cauda flamejante.",
        evolucao: "Evoluções:  Raboot (#814) e Cinderace (#815).",
        personalidade:" Personalidade: Rápido, competitivo e um pouco impulsivo.",
        imagem: "./img/scorbunny.png",
        imagem2: "./img/raboot.png",
        imagem3: "./img/cinderace.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Sobble - #816",
        titulo2: "8ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características:  Um pequeno lagarto azul com uma lágrima na cabeça.",
        evolucao: "Evoluções:  Drizzile (#817) e Inteleon (#818).",
        personalidade:" Personalidade: Tímido, inteligente e um pouco ansioso.",
        imagem: "./img/sobble.png",
        imagem2: "./img/drizzile.png",
        imagem3: "./img/inteleon.png",
        tipoClasse: "agua"
    },
    {
        titulo: "Sprigatito - #906",
        titulo2: "9ª Geração",
        tipo: "Tipo: Planta.",
        descricao: " Características: Um pequeno gato com pelagem verde e olhos castanhos.",
        evolucao: "Evoluções: Floragato (#907) e Meowscarada (#908).",
        personalidade:" Personalidade: Elegante, confiante e um pouco reservado.",
        imagem: "./img/sprigatito.png",
        imagem2: "./img/floragato.png",
        imagem3: "./img/meowscarada.png",
        tipoClasse: "planta"
    },
    {
        titulo: "Fuecoco - #909",
        titulo2: "9ª Geração",
        tipo: "Tipo: Fogo.",
        descricao: " Características: Um pequeno crocodilo com uma chama na ponta da cauda.",
        evolucao: "Evoluções:  Crocalor (#910) e Skeledirge (#911).",
        personalidade:" Personalidade: Enérgico, competitivo e um pouco imprudente.",
        imagem: "./img/fuecoco.png",
        imagem2: "./img/crocalor.png",
        imagem3: "./img/skeledirge.png",
         tipoClasse: "fogo"
    },
    {
        titulo: "Quaxly - #912",
        titulo2: "9ª Geração",
        tipo: "Tipo: Água.",
        descricao: " Características: Um pequeno pato com uma crista azul e olhos castanhos.",
        evolucao: "Evoluções: Quaxwell (#913) e Quaquaval (#914).",
        personalidade:" Personalidade: Sério, determinado e um pouco perfeccionista.",
        imagem: "./img/quaxly.png",
        imagem2: "./img/quaxwell.png",
        imagem3: "./img/quaquaval.png",
        tipoClasse: "agua"
    },
    
    
    
];